# Generated by Django 5.0.4 on 2024-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_information"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="information",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
