# Generated by Django 5.0.4 on 2024-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="total_price",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gateway_page_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sessionkey",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
