# Generated by Django 5.0.4 on 2024-04-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_price_orderitem_total_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address2",
            new_name="address_2",
        ),
    ]
