# Generated by Django 5.0.4 on 2024-05-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("paid", "Paid"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("received", "Received"),
                    ("returned", "Returned"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
